### ISSUE TITLE
Given final block not properly padded.

### ISSUE THREAD

**Issue by jamesecker** [phillipsdata/phpaes#5]
I have used your example code to test, but when I use [https://www.devglan.com/online-tools/aes-encryption-decryption](url) to decode the test I receive the following error:

Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

Is there something I am missing?

**Comment by clphillips** [comment]
The link you provided likely uses a different padding scheme, probably PKCS5. This library currently only supports null byte padding.

Try testing using OFB or CFB modes. More info on block cipher padding can be found here cipher https://www.cryptosys.net/pki/manpki/pki_paddingschemes.html
