### ISSUE TITLE
Does this *really* support PHP4, like your website homepage claims ?

### ISSUE THREAD

**Issue by gitcnd** [phillipsdata/phpaes#9]
If not - can you please include the PHP4 version ?

from phpaes.com:-

" phpAES is a PHP 5 (PHP 4 version now included) class implementation of 128, 192, and 256 bit AES encryption cipher. I "

**Comment by clphillips** [comment]
https://github.com/phillipsdata/phpaes/releases/tag/1.0.0 supports PHP 4, but that version of PHP was abandoned in 2008, so expecting software to support it is asking a bit much. I suggest upgrading to PHP 7.4 as soon as possible.

When we added PHP 4 support in 2008 it was only our intention for it to be used for a short time by those still transitioning to PHP 5.

**Comment by gitcnd** [comment]
Cool - thanks... in the meantime, I converted it back to a working PHP4 version.  Not too shabby, given that I don't know PHP...  The upgrade advice is obvious, but of course impractical (and unsustainable), but thanks for pointing out that 7 seems to be the right version to go with for the future.
